name: flexiblelayout
description: easy to divide layout.
repository: https://github.com/dorage/flutter_flexiblelayout

version: 1.0.1+1

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
